spring:
  datasource:
    url: jdbc:mysql://localhost:3306/test01?useSSL=false&useUnicode=true&characterEncoding=utf-8&serverTimezone=UTC
    username: root
    password: root
mybatis:
  mapper-locations: mappers/*.xml